# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
# app/config/security.yml
security:
     encoders:
          AppBundle\Entity\User: bcrypt
     providers:
          user:
               entity:
                    class: AppBundle\Entity\User
                    property: username
     firewalls:
          dev:
               pattern: ^/(_(profiler|wdt)|css|images|js)/
               security: false
          main:
               provider: user
               anonymous: ~
               form_login:
                    login_path: login
                    check_path: login
                    default_target_path: movie_list
               logout:
                    path: logout
                    target: homepage
     access_control:
          - { path: ^/films, roles: ["ROLE_USER","ROLE_ADMIN"] }
