<?php

namespace AppBundle\Repository;

/**
 * DescriptionSheetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DescriptionSheetRepository extends \Doctrine\ORM\EntityRepository
{
}
