<?php

namespace AppBundle\Repository;

/**
 * FicheDescriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FicheDescriptionRepository extends \Doctrine\ORM\EntityRepository
{
}
