<?php

namespace AppBundle\Repository;

/**
 * RoleActorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleActorRepository extends \Doctrine\ORM\EntityRepository
{
}
